### ISSUE TITLE
Add onScroll callback prop on VirtualContainer

### ISSUE THREAD

**Issue by aquaductape** [minht11/solid-virtual-container#1]
I know you provide already scrollTarget prop for VirtualContainer and use that to add events, but providing onScroll callback prop is a little cleaner. [React window](https://github.com/bvaughn/react-window) has it and it can be useful such as determining whether the scrollable container is at the beginning or end ect.

**Comment by minht11** [comment]
Do you want `onScroll` to be fired every time `scrollTarget` element is scrolled? Doing that would be quite simple, if you want `onScroll` to be called only when container is visible that's gonna bit more tricky.

If first option is enough I think I would be willing to implement it.
Also what information should be passed to `onScroll` callback? An actual event or some other data?

**Comment by aquaductape** [comment]
I assumed for the add/remove elements procedure, you used a scroll event. But this appears not to be the case.

In that case, no need to add the `onScroll` prop
