### ISSUE TITLE
If no width given (such as in the README example), width is 0

### ISSUE THREAD

**Issue by hangtwenty** [minht11/solid-virtual-container#2]
I think you can actually see this in the CodeSandbox demo linked from the README; there are 3 instances of `<VirtualContainer>` but only 2 are visible - the ones that specify width - the other one has elements of width 0. (And adding a `width` parameter to its `itemSize` makes it visible.)

**Comment by floer32** [comment]
`itemSize` seems like is is hardcoded to take a number for height/weight, and it puts that in a `px` height. Is there a way to specify item width of `"100%"` (when it's a vertical list)?

**Comment by minht11** [comment]
In the demo there are 4 instances of `<VirtualContainer>` one list and one grid in the same scroll container for vertical and horizontal scroll directions. They render fine for me.

With vertical direction list only `height` property inside `itemSize` needs to be specified for list to work, other styling is up to you, set list item css styles to `width: 100%` and it should work correctly, demo does this as well. Or if you really don't want to use css, `itemSize` can take a function which passes container dimensions as an argument and you can use values from there to set the width, though for basic stuff I would just use css.

**Comment by abhijeetChawla** [comment]
i ran it to the same issue, solved it the way as you said by adding the class on the child element.

**Comment by minht11** [comment]
I updated readme with few comments, on how to size list items correctly, I hope it makes things bit clearer.
