### ISSUE TITLE
[Safari] scroll bar doesn't work on the vertical example

### ISSUE THREAD

**Issue by goenning** [minht11/solid-virtual-container#4]
While trying this demo ( https://codesandbox.io/s/minht11solid-virtual-container-demo-pk74r ) I noticed the scroll bar doesn't work on Safari 15, but works fine on Chrome.

The horizontal scroller works fine on Chrome and Safari.

Any ideas what could be missing?

**Comment by minht11** [comment]
Safari with an overlay scrollbar seems to be forwarding pointer events to the content and not to the scrollbar. I added horizontal padding to the demo as a temporary fix, other than that your best bet would be to open bug in https://bugs.webkit.org/
